config/routes.rb
ProfilePage::Application.routes.draw do

  resources :users

    root  :to => "users#index"

    get "profile/index"

end

app/models/user.rb
class User < ActiveRecord::Base
attr_accessible :name
attr_accessible :genre
attr_accessible :location
attr_accessible :avatar 
has_attached_file :avatar,
		  :styles => { :medium => "300x300>",
                                 :thumb => "100x100>" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProfilePage</title>
  <%= stylesheet_link_tag    "application", "960",:media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container_16">
	<div class = "grid_16 pull_1">
	<img src ="/assets/home.jpg" />		 
	</div>
<%= yield %>
</div>
<!-- end .container_16 -->
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :genre %><br />
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
	<%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>    
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to user.name, user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<body bgcolor="#F3F3F3">


	<div class="clear">&nbsp;</div> 
	<div class="grid_4 pull_1"  style = " border: 1px solid black; border-color:#C8E2E3;">
		<div id="profile_name" style ="color:#78CDE1;text-align:center;">		
		<%= @user.name %><br>
		 <%= @user.genre %><br>
		<%= @user.location %><br>
		</div>
		<div id="profile_image" style="padding-left:10px;">
		<center><%= image_tag @user.avatar.url(:thumb) %></center>
		</div>
		<div id="profile_message" style = "border:1px solid black;border-color:#C8E2E3;text-align:center;font-size:12px">
		    Message | + Connections
		</div>
		<table style = "font-size:12px"><tr><td>*services listed here</td><td> *in a table</td></tr>
		  	<tr><td>*as bullet points</td><td>*veryneatly</td></tr>
		</table>
		<div id="band_members" style = "border:1px solid black;border-color:#C8E2E3;">
		<table style = "font-size:12px">
			<th><u>BandMembers</u></th>
			<th>|Connections</th>
			<tr><td>BandMembers</td></tr>
			<tr>
				<td><img src="/assets/profile.gif" height = "40" width = "70" alt ="image_here"/></td>
				<td>MemberName<br>Job/Instruments</td>
			</tr>
			<tr>
				<td><img src="/assets/profile.gif" height = "40" width = "70" alt ="image_here"/></td>
				<td>MemberName<br>Job/Instruments</td>
			</tr>
			<tr>
				<td><img src="/assets/profile.gif" height = "40" width = "70" alt ="image_here"/></td>
				<td>MemberName<br>Job/Instruments</td>
			</tr>
			<tr>
				<td><img src="/assets/profile.gif" height = "40" width = "70" alt ="image_here"/></td>
				<td>MemberName<br>Job/Instruments</td>
			</tr>
		</table>
		</div>
		
	</div>
	<div class="grid_7 pull_1" >
		<center><a href="#" style="font-size:20px">About</a>|<a href="#" style="font-size:20px">Portfolio</a>|<a href="#" style="font-size:20px">Ziqqu Report</a> </center>
		<div id="text_box"  style = "width: 420px; height:400px; border: 1px solid black;border-color:#C8E2E3; font-color:">
			<br><br>

			<center>This is for textbox...........</center>
			<br><br><hr>
		<div id="add_another_topic">
			<br><br>
			<center><h4>AddAnotherTopic</h4></center>
			<br><br>
		</div>
		</div>
	</div>
	<div class="grid_4"  style = "width:270px; border: 1px solid black;">
		 <center><a href="#" style="font-size:17px">Music</a>|<a href="#" style="font-size:17px">Photos</a>|<a href="#" style="font-size:17px">Videos</a>|<a href="#" style="font-size:17px">Touring/events</a>
	</div>